site_name: Jonatan Rasmussen
docs_dir: .
site_dir: ../site
repo_url: https://github.com/JonatanRasmussen/JonatanRasmussen.github.io

theme:
  language: en
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.expand
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - glightbox
  - same-dir

extra:
  social:
    - icon: material/email
      link: mailto:jonatan.j.k.rasmussen@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/JonatanRasmussen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonatan-rasmussen-b07193267/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@jonatanrasmussen

nav:
  - Home: README.md
  - Project: projects_main.md
  - CV: cv.md
  - Personal Archive: personal_archive.md